uiMode: ImGui
dpi: 1
loadedFonts:
  - fontName: Saira
    fontPath: SairaCondensed-Light.ttf
    isDefault: true
    fontSizes:
      - 24
      - 36
      - 46
      - 48
  - fontName: FA
    fontPath: ""
    isDefault: false
    fontSizes:
      - 24
      - 36
      - 48