name: Build
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
            path: staging
        
        - name: Download frc and build infocards
          run: |
            Invoke-WebRequest "http://adoxa.altervista.org/freelancer/dlt.php?f=frc" -OutFile ${{ github.workspace }}\frc.zip
            Expand-Archive ${{ github.workspace }}\frc.zip
            Start-Process -Wait ${{ github.workspace }}\frc\frc.exe -ArgumentList "staging\mod-assets\infocard_imports.frc", "staging\mod-assets\EXE\BmodInfocards.dll"

        - name: Download the Freelancer XML Project and Compile XML files to UTF
          run: |
            Invoke-WebRequest "http://adoxa.altervista.org/freelancer/dlt.php?f=xmlproject" -OutFile ${{ github.workspace }}\xmlproject.zip
            Expand-Archive ${{ github.workspace }}\xmlproject.zip
            $destination = "${{ github.workspace }}\staging\mod-assets\DATA\"
            Get-ChildItem "staging\mod-assets\XML" | ForEach-Object -Process Write-Host "$_.FullName"


        - name: Add mod zip
          run: |
            type NUL > ${{ github.workspace }}\Assets\Mod\freelancerhd.7z
          shell: cmd
            
        - name: Compile script
          run: |
            "%programfiles(x86)%\Inno Setup 6\iscc.exe" "se